<?php
    /**
     *  Author : Dream <34650064@QQ.com>
     *  Encoding : UTF-8
     *  Separator : Unix and OS X (\n)
     *  File Name : Auth.php
     *  Create Date : 2022/5/14 23:27
     *  Version : 0.1
     *  Copyright : skylong Project Team Copyright (C)
     *  Email Address : yxly330@126.com
     *  license http://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh
     */
    namespace app\apiadmin\controller;
    class Auth extends BaseController {

        public function initialize() {
            parent::initialize(); // TODO: Change the autogenerated stub
        }

        public function login(){

        }

    }