<?php
    /**
     *  Encoding : UTF-8
     *  Separator : Unix and OS X (\n)
     *  File Name : BaseController.php
     *  Create Date : 2022/3/13 19:18
     *  Version : 0.1
     *  Copyright : skylong Project Team Copyright (C)
     *  license http://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh
     */
    namespace app\apiadmin\controller;
    class BaseController extends \app\common\controller\BaseController {

        public function initialize() {
            header('Access-Control-Allow-Origin: *');
            header('Access-Control-Allow-Headers: *');
            parent::initialize(); // TODO: Change the autogenerated stub
        }

        public function pdata(){
            return json_decode(file_get_contents("php://input"),true);
        }

        public function ret($data){
            echo json_encode($data);
        }


    }