<?php
namespace app\admin\controller;


use app\common\controller\AdminController;
use think\Db;
use think\facade\Cookie;

class Index extends AdminController
{

    public function initialize() {
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    public function index()
    {
        $menus = $this->getMenus();
        $this->assign('menus',$menus);
        $is_new = $this->request->param('is_new',0);
        if($is_new == 1){

            return $this->fetch('index_new');
        }
        return $this->fetch();
    }

    public function home()
    {
        return $this->fetch('home/index');
    }

    public function kehuAdd()
    {
        $result = DB::name('khlist')->field('Ksource,Kproduct,Ktype,Ktag')->select();
        return json($result);
        return $this->fetch('kehu/add');
    }

    public function kehuList()
    {
        return $this->fetch('kehu/list');
    }

    public function iconLibs()
    {
        return $this->fetch('iconLibs');
    }



}
