<?php
namespace app\admin\controller;


use app\common\controller\BaseController;
use think\Controller;
use think\Db;
use app\admin\model\System as SysData;
use think\facade\Cookie;
use think\facade\Session;
use think\facade\Request;

class Login extends BaseController
{

    public function initialize() {
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    //验证登录
    public function index(){
        if(Cookie::has('name')){
            $this->success('登录成功','/admin/');
        }
        $data=($this->request->param());
        if(@$data['username']){
            $result = Db::name('admin')
                ->where('username', $data['username'])
                ->where('password', md5($data['password']))
                ->find();

            if(@$result){
                $data = [
                    'code' => 1,
                    'name' => $result['name'],
                    'tokenName' => '8888aaaaaaccccc',
                    'id' => $result['id'],
                    'group_id'=>$result['group_id']
                ];
                Cookie::set('name',$data['name'],config('cookie.expire'));
                Cookie::set('id',$data['id'],config('cookie.expire'));
                Cookie::set('group_id',$data['group_id'],config('cookie.expire'));
                Cookie::set('area_id',$result['area_id'],config('cookie.expire'));
                Cookie::set('school_id',$result['school_id'],config('cookie.expire'));
                Cookie::set('tokenName',$data['tokenName'],config('cookie.expire'));
                Session::set('name',$data['name']);
                return json($data);
            }
            $data = [
                'code' => 2
            ];
            return json($data);
        }
        if(config('sys_data.login_tmp')){
            return $this->fetch('index'.config('sys_data.login_tmp'));
        }
        return $this->fetch();
    }

}
