<?php
    /**
     *  新闻类
     *  Encoding : UTF-8
     *  Separator : Unix and OS X (\n)
     *  File Name : News.php
     *  Create Date : 2021/12/29 13:55
     *  Version : 0.1
     *  Copyright : skylong Project Team Copyright (C)
     *  license http://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh
     */

    namespace app\admin\controller;
    use app\common\controller\AdminController;
    use \think\facade\Cookie;

    class News extends AdminController {

        public function initialize() {
            parent::initialize(); // TODO: Change the autogenerated stub
        }

        public function index(){
            $where = [];
            if($this->request->isPost()){
                $page = $this->request->post('page',$this->page);
                $limit = $this->request->post('limit',$this->limit);
                $admin_id = Cookie::get('id');
                if((int)cookie('group_id') !== config('rx.groupId')){
                    $where[] = ['n.admin_id','=',$admin_id];
                }
                // 处理搜索信息
                $news_type_id = $this->request->param('news_type_id',0);
                if(!empty($news_type_id)){
                    $where[] = ['n.news_type_id','=',$news_type_id];
                }
                $is_top = $this->request->param('is_top',-1);
                if(intval($is_top) >= 0 && $is_top !== ''){
                    $where[] = ['n.is_top','=',$is_top];
                }
                $state = $this->request->param('state',-1);
                if(intval($state) >= 0 && $state !== ''){
                    $where[] = ['n.state','=',$state];
                }
                $title = $this->request->param('title','');
                if(!empty($title)){
                    $where[] = ['n.title','like',"%{$title}%"];
                }
                $list = db('news')
                    ->alias('n')
                    ->join('news_type nt','n.news_type_id = nt.id and nt.state = '.$this->status['NORMAL'])
                    ->join('admin a','n.admin_id = a.id')
                    ->where($where)
                    ->field("n.id,nt.name type,n.title,n.show_all,n.is_top,FROM_UNIXTIME(n.create_time) create_time,n.state,a.name admin_name")
                    ->limit(($page-1)*$limit,$limit)
                    ->select();
                $total = db('news')
                    ->alias('n')
                    ->join('news_type nt','n.news_type_id = nt.id and nt.state = '.$this->status['NORMAL'])
                    ->where($where)
                    ->count();
                return $this->returnTabelJson($list,'查询成功',$total);
            }
            return $this->fetch();
        }

        public function add(){
            if($this->request->isPost()){
                $data = [];
                $image = $this->request->param('image','');
                if(empty($image)){
                    return $this->returnJson([],'创建新闻失败：封面未上传');
                }
                $data['image'] = $image;
                $title = $this->request->param('title','');
                if(empty($title)){
                    return $this->returnJson([],'创建新闻失败：新闻标题不能为空');
                }
                $data['title'] = $title;
                $news_type_id = $this->request->param('news_type_id',0);
                if(empty($news_type_id)){
                    return $this->returnJson([],'创建新闻失败：新闻类型未选择');
                }
                $data['news_type_id'] = $news_type_id;

                $description = $this->request->param('description','');
                if(empty($description)){
                    return $this->returnJson([],'创建新闻失败：新闻描述不能为空');
                }
                $data['description'] = $description;

                // 获取当前登陆人所属区域，判断是否为总区管理员
                $area_id = Cookie::has('area_id')?Cookie::get('area_id'):0;
                if(!check_admin_area()){
                    // 分区管理员
                    $data['show_all'] = 0;
                    $data['area_ids'] = ','.$area_id.',';
                }else{
                    $show_all = $this->request->param('show_all',0);
                    if($show_all == 'on'){
                        $data['show_all'] = 1;
                    }else{
                        $area_ids = $this->request->param('area','');
                        if(empty($area_ids)){
                            return $this->returnJson([],'创建新闻失败：显示区域未选择');
                        }
                        $data['area_ids'] = ','.implode(',',$area_ids).',';
                    }
                }

                $content = $this->request->param('content','');
                if(empty($content)){
                    return $this->returnJson([],'创建新闻失败：新闻内容不能为空');
                }
                $data['content'] = $content;

                $is_top = $this->request->param('is_top',0);
                if($is_top == 'on'){
                    $data['is_top'] = 1;
                }
                $sort = $this->request->param('sort',0);
                $data['sort'] = $sort;
                $data['create_time'] = time();
                $data['admin_id'] = \cookie('id');
                $id = db('news')->insertGetId($data);
                if($id > 0){
                    insert_admin_log('创建新闻成功');
                    return $this->returnJson(['id'=>$id],'创建新闻成功',1);
                }
                return $this->returnJson([],'创建新闻失败');
            }
            // 区域列表
            $area['province'] = action('admin/school/addressList',['id'=>0,'type'=>1]);
            $area['city'] = [];
            $area['area'] = action('admin/school/addressList',['id'=>0,'type'=>1]);
            $types = db('news_type')->where("state = 1")->select();
            return $this->fetch('save_news',compact('area','types'));
        }

        public function edit(){
            $id = $this->request->param('id',0);
            if($this->request->isPost()){
                $data = $this->request->param();
                $update = [];
                if(isset($data['image'])){
                    if(empty($data['image'])){
                        return $this->returnJson([],'更新新闻失败：封面未上传');
                    }
                    $update['image'] = $data['image'];
                }
                if(isset($data['title'])){
                    if(empty($data['title'])){
                        return $this->returnJson([],'更新新闻失败：新闻标题不能为空');
                    }
                    $update['title'] = $data['title'];
                }
                if(isset($data['description'])){
                    if(empty($data['description'])){
                        return $this->returnJson([],'更新新闻失败：新闻描述不能为空');
                    }
                    $update['description'] = $data['description'];
                }
                if(isset($data['news_type_id'])){
                    if(empty($data['news_type_id'])){
                        return $this->returnJson([],'更新新闻失败：新闻类型未选择');
                    }
                    $update['news_type_id'] = $data['news_type_id'];
                }
                if(isset($data['content'])){
                    if(empty($data['content'])){
                        return $this->returnJson([],'更新新闻失败：新闻内容不能为空');
                    }
                    $update['content'] = $data['content'];
                }
                // 获取当前登陆人所属区域，判断是否为总区管理员
                if(check_admin_area()){
                    if(isset($data['show_all'])){
                        if($data['show_all'] == 'on'){
                            $data['show_all'] = 1;
                            $update['area_ids'] = '';
                        }else{
                            if(!isset($data['area']) || empty($data['area'])){
                                return $this->returnJson([],'更新新闻失败：显示区域未选择');
                            }
                            $update['area_ids'] = ','.implode(',',$data['area']).',';
                            $data['show_all'] = 0;
                        }
                        $update['show_all'] = $data['show_all'];
                    }
                }
                if(isset($data['is_top'])){
                    if($data['is_top'] == 'on'){
                        $data['is_top'] = 1;
                    }
                    $update['is_top'] = $data['is_top'];
                }
                if(isset($data['state'])){
                    $update['state'] = $data['state'];
                }
                if(isset($data['sort'])){
                    $update['sort'] = $data['sort'];
                }
                $res = db("news")->where("id = {$id}")->update($update);
                if($res !== false){
                    insert_admin_log('更新新闻成功');
                    return $this->returnJson(['id'=>$id],'更新新闻成功',1);
                }
                return $this->returnJson([],'更新新闻失败');
            }
            $info = db('news')->where("id = {$id}")->find();
            $info['url'] = '/admin/news/edit';
            // 区域列表
            $area['province'] = action('admin/school/addressList',['id'=>0,'type'=>1]);
            $area['city'] = [];
            $area['area'] = db('area')->where("p_id != 0")->select();;
            $types = db('news_type')->where("state = 1")->select();
            return $this->fetch('save_news',compact('info','area','types'));
        }

        public function del(){
            $id = $this->request->param('id',0);
            $res = db('news')->where("id = {$id}")->delete();
            if($res !== false){
                insert_admin_log('删除新闻');
                return $this->returnJson([],'删除成功',1);
            }
            return $this->returnJson([],'删除失败');
        }
    }