<?php
    /**
     *  项目
     *  Encoding : UTF-8
     *  Separator : Unix and OS X (\n)
     *  File Name : Project.php
     *  Create Date : 2021/12/31 8:20
     *  Version : 0.1
     *  Copyright : skylong Project Team Copyright (C)
     *  license http://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh
     */

    namespace app\admin\controller;
    use app\common\controller\AdminController;

    class Project extends AdminController {

        public function initialize() {
            parent::initialize(); // TODO: Change the autogenerated stub
        }

        public function index(){
            if($this->request->isPost()){
                $page = $this->request->post('page',$this->page);
                $limit = $this->request->post('limit',$this->limit);
                $list = db('project')
                    ->limit(($page-1)*$limit,$limit)
                    ->select();
                $total = db('project')
                    ->count();
                return $this->returnTabelJson($list,'查询成功',$total);
            }
            return $this->fetch();
        }

        public function add(){
            if($this->request->isPost()){
                $name = $this->request->post('name','');
                if(empty($name)){
                    return $this->returnJson([],'创建项目失败：项目名称不能为空');
                }
                $sort = $this->request->post('sort',0);
                $id = db('project')->insertGetId([
                    'name' => $name,
                    'sort' => $sort,
                    'admin_id' => cookie('id'),
                    'create_time' => time()
                                           ]);
                if($id > 0){
                    insert_admin_log('创建项目成功');
                    return $this->returnJson(['id'=>$id],'创建项目成功',1);
                }
                return $this->returnJson([],'创建项目失败');
            }
            return $this->fetch('save');
        }

        public function edit(){
            $id = $this->request->param('id',0);
            if($this->request->isPost()){
                $data = $this->request->param();
                $update = [];
                if(isset($data['name'])){
                    if(!empty($data['name'])){
                        $update['name'] = $data['name'];
                    }else{
                        return $this->returnJson([],'更新项目失败：项目名称不能为空');
                    }
                }
                $sort = $this->request->post('sort','sss');
                if($sort !== 'sss'){
                    $update['sort'] = $sort;
                }
                $state = $this->request->post('state',-999);
                if($state !== -999){
                    $update['state'] = $state;
                }
                $res = db('project')->where("id = {$id}")->update($update);
                if($res !== false){
                    insert_admin_log('更新项目成功');
                    return $this->returnJson(['id'=>$id],'更新项目成功',1);
                }
                return $this->returnJson([],'更新项目失败');
            }
            $info = db('project')->where("id = {$id}")->find();
            $info['url'] = '/admin/project/edit';
            return $this->fetch('save',compact('info'));
        }

        public function del(){
            $id = $this->request->param('id',0);
            $res = db('project')->where("id = {$id}")->delete();
            if($res !== false){
                insert_admin_log('删除项目成功');
                return $this->returnJson([],'删除成功',1);
            }
            return $this->returnJson([],'删除失败');
        }

    }