<?php
/**
 *  Encoding : UTF-8
 *  Separator : Unix and OS X (\n)
 *  File Name : school.php
 *  Create Date : 2021/12/31 9:04
 *  Version : 0.1
 *  Copyright : skylong School Team Copyright (C)
 *  license http://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh
 */

namespace app\admin\controller;

use app\common\controller\AdminController;

class School extends AdminController
{

    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    public function index()
    {
        if ($this->request->isPost()) {
            $page = $this->request->post('page', $this->page);
            $limit = $this->request->post('limit', $this->limit);
            $list = db('school')
                ->alias('sv')
                ->join('area s', 's.id = sv.area_id and s.state =' . $this->status['NORMAL'])
                ->field('sv.id,s.name area_name,sv.name,sv.state,sv.level,sv.accept_line,sv.quality_line')
                ->limit(($page - 1) * $limit, $limit)
                ->select();
            $total = db('school')
                ->alias('sv')
                ->join('area s', 's.id = sv.area_id and s.state =' . $this->status['NORMAL'])
                ->field('sv.id,s.name area_name,sv.name,sv.state')
                ->count();
            return $this->returnTabelJson($list, '查询成功', $total);
        }
        return $this->fetch();
    }

    public function add()
    {
        if ($this->request->isPost()) {
            $name = $this->request->post('name', '');
            if (empty($name)) {
                return $this->returnJson([], '创建学校失败：学校名称不能为空');
            }
            $province_id = $this->request->post('province_id', 0);
            $city_id = $this->request->post('city_id', 0);
            $area_id = $this->request->post('area_id', 0);
            if (empty($area_id)) {
                return $this->returnJson([], '创建学校失败：所属科目请选择');
            }

            $sort = $this->request->post('sort', 0);
            $level = $this->request->post('level', 1);
            $accept_line = $this->request->post('accept_line', 0);
            $quality_line = $this->request->post('quality_line', 0);
            $id = db('school')->insertGetId([
                'name' => $name,
                'sort' => $sort,
                'province_id' => $province_id,
                'city_id' => $city_id,
                'area_id' => $area_id,
                'level' => $level,
                'accept_line' => $accept_line,
                'quality_line' => $quality_line,
                'admin_id' => cookie('id'),
                'create_time' => time()
            ]);
            if ($id > 0) {
                insert_admin_log('创建学校成功');
                return $this->returnJson(['id' => $id], '创建学校成功', 1);
            }
            return $this->returnJson([], '创建学校失败');
        }
        $area = [];
        $area['province'] = $this->addressList(0, 1);
        $area['city'] = [];
        $area['area'] = [];
        return $this->fetch('save', compact('area'));
    }



    public function edit()
    {
        $id = $this->request->param('id', 0);
        if ($this->request->isPost()) {
            $data = $this->request->param();
            $update = [];
            if (isset($data['name'])) {
                if (!empty($data['name'])) {
                    $update['name'] = $data['name'];
                } else {
                    return $this->returnJson([], '更新学校失败：学校名称不能为空');
                }
            }
            if (isset($data['area_id'])) {
                if (!empty($data['area_id'])) {
                    $update['area_id'] = $data['area_id'];
                } else {
                    return $this->returnJson([], '更新学校失败：所属科目请选择');
                }
            }
            $sort = $this->request->post('sort', 'sss');
            if ($sort !== 'sss') {
                $update['sort'] = $sort;
            }
            $state = $this->request->post('state', -999);
            if ($state !== -999) {
                $update['state'] = $state;
            }
            $level = $this->request->post('level', 1);
            $accept_line = $this->request->post('accept_line', 0);
            $quality_line = $this->request->post('quality_line', 0);
            $update['level'] = $level;
            $update['accept_line'] = $accept_line;
            $update['quality_line'] = $quality_line;
            $res = db('school')->where("id = {$id}")->update($update);
            if ($res !== false) {
                insert_admin_log('更新学校成功');
                return $this->returnJson(['id' => $id], '更新学校成功', 1);
            }
            return $this->returnJson([], '更新学校失败');
        }
        $info = db('school')->where("id = {$id}")->find();
        $area['province'] = $this->addressList(0, 1);
        $area['city'] = $this->addressList($info['province_id'], 1);
        $area['area'] = $this->addressList($info['city_id'], 1);
        $info['url'] = '/admin/school/edit';
        return $this->fetch('save', compact('info', 'area'));
    }

    public function del()
    {
        $id = $this->request->param('id', 0);
        if (db('class_group')->where("school_id = {$id}")->count() > 0) {
            return $this->returnJson([], '删除学校失败：该学校下存在班组');
        }
        if (db('user')->where("school_id = {$id}")->count() > 0) {
            return $this->returnJson([], '删除学校失败：该学校下存在学生');
        }
        $res = db('school')->where("id = {$id}")->delete();
        if ($res !== false) {
            insert_admin_log('删除学校成功');
            return $this->returnJson([], '删除学校成功', 1);
        }
        return $this->returnJson([], '删除学校失败');
    }

    public function addressList($id, $type = 0, $area_type = 0)
    {
        $res = db('area')->where("p_id = $id and state=1")->select();
        if ($type == 1) {
            return $res;
        }
        if ($res) {
            return json(['code' => 100, 'msg' => '获取成功', 'data' => $res]);
        } else {
            return json(['code' => 0, 'msg' => '请添加县区']);
        }
    }
}