<?php
    /**
     *  Encoding : UTF-8
     *  Separator : Unix and OS X (\n)
     *  File Name : Admin.php
     *  Create Date : 2022/6/5 21:58
     *  Version : 0.1
     *  Copyright : skylong Project Team Copyright (C)
     *  license http://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh
     */
    namespace app\index\controller;
    class Admin extends BaseController {

        public function initialize() {
            parent::initialize(); // TODO: Change the autogenerated stub
        }

        public function index(){
            $page = $this->request->param('page',1);
            $limit = $this->request->param('limit',10);
            $where = [];
            $username = $this->request->param('account','');
            if(!empty($username)){
                $where[] = ['a.username','like',"%{$username}%"];
            }
            $name = $this->request->param('name','');
            if(!empty($name)){
                $where[] = ['a.name','like',"%{$name}%"];
            }
            $phone = $this->request->param('mobile','');
            if(!empty($phone)){
                $where[] = ['a.phone','like',"%{$phone}%"];
            }
            $list = db('admin')
                ->alias('a')
                ->join('auth_group b','b.id=a.group_id')
                ->join('area ae','a.area_id = ae.id','left')
                ->field("a.id,a.username account,a.password,a.name,a.group_id,a.phone mobile,a.email,b.name as qxName,a.area_id,ifnull(ae.name,'') area_name")
                ->where($where)
                ->limit(($page-1)*$limit,$limit)
                ->select();
            $total = db('admin')
                ->alias('a')
                ->where($where)
                ->join('auth_group b','b.id=a.group_id')
                ->count();

            return $this->returnJson(['totalElements'=>$total,'content'=>$list],'获取成功',200);
        }

        public function add(){
            $account = $this->request->param('account','');
            $email = $this->request->param('email','');
            $mobile = $this->request->param('mobile','');
            $name = $this->request->param('name','');
            $password = $this->request->param('password','');

            $roleIds = $this->request->param('roleIds',[]);

            $userId = db('admin')->insertGetId([
                'username'=>$account,
                'password'=>md5($password),
                'name'=>$name,
                'phone'=>$mobile,
                'email'=>$email,
                'group_id'=>$roleIds[0],
             ]);
            return $this->returnJson($userId,'操作成功',200);
        }

        public function edit(){
            $userId = $this->request->param('id',0);
            $account = $this->request->param('account','');
            $email = $this->request->param('email','');
            $mobile = $this->request->param('mobile','');
            $name = $this->request->param('name','');
            $password = $this->request->param('password','');

            $roleIds = $this->request->param('roleIds',[]);

            $data = [
                'username'=>$account,
                'name'=>$name,
                'phone'=>$mobile,
                'email'=>$email,
                'group_id'=>$roleIds[0],
             ];
            if(!empty($password)){
                $data['password'] = md5($password);
            }
            db('admin')->where("id = {$userId}")->update($data);
            return $this->returnJson([],'操作成功',200);
        }

        public function detail($userId = 0){
            $data = db('admin')->alias('a')->where('a.id', $userId)->field('a.id,a.username account,"" password,a.name,a.group_id,a.phone mobile,a.email')->find();
            $data['roleIds'] = [$data['group_id']];
            return $this->returnJson($data,'获取成功',200);
        }

        public function del($userId = 0){
            db('admin')->where('id', $userId)->delete();
            return $this->returnJson([],'删除成功',200);
        }

        public function getOneUser(){
            $name = $this->request->param('name','');
            $data = db('admin')->alias('a')->where('a.username', $name)->field('a.id,a.username account,a.password,a.name,a.group_id,a.phone mobile,a.email')->find();
            return $this->returnJson($data,'获取成功',200);
        }
    }