<?php
    /**
     *  Encoding : UTF-8
     *  Separator : Unix and OS X (\n)
     *  File Name : Admin.php
     *  Create Date : 2022/6/5 21:58
     *  Version : 0.1
     *  Copyright : skylong Project Team Copyright (C)
     *  license http://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh
     */
    namespace app\index\controller;
    class Role extends BaseController {

        public function initialize() {
            parent::initialize(); // TODO: Change the autogenerated stub
        }

        public function index(){
            $page = $this->request->param('page',1);
            $limit = $this->request->param('limit',10);
            $map[] = ['id','>',0];
            $name = $this->request->param('name','');
            if(!empty($name)){
                $map[] = ['name','like',"%{$name}%"];
            }
            $list = model('authGroup')->where($map)->order("id desc")->limit(($page-1)*$limit,$limit)->field("*,status enabled,if(type = 1,'后台用户','前台用户') remark")->select();
            $total = model('authGroup')->where($map)->count();

            return $this->returnJson(['totalElements'=>$total,'content'=>$list],'获取成功',200);
        }

        public function detail($roleId = 0){
            $data = model('authGroup')->alias('a')->where('a.id', $roleId)->field("*,status enabled,if(type = 1,'后台用户','前台用户') remark")->find();
            $rules = explode(',',$data['rules']);
            $menuIds = [];
            foreach ($rules as $key => $item){
                $menuIds[] = intval($item);
            }
            $data['menuIds'] = $menuIds;
            return $this->returnJson($data,'获取成功',200);
        }

        public function getOneRole($name = ''){
            $name = $this->request->param('name','');
            $data = model('authGroup')->alias('a')->where('a.name', $name)->field("*,status enabled,if(type = 1,'后台用户','前台用户') remark")->find();
            return $this->returnJson($data,'获取成功',200);
        }

        public function enable_list(){
            $map[] = ['status','=',1];
            $list = model('authGroup')->where($map)->order("id desc")->field("*,if(type = 1,'后台用户','前台用户') remark")->select();
            return $this->returnJson($list,'获取成功',200);
        }
    }