<?php
    /**
     *  Encoding : UTF-8
     *  Separator : Unix and OS X (\n)
     *  File Name : Setting.php
     *  Create Date : 2022/7/15 13:37
     *  Version : 0.1
     *  Copyright : skylong_ii Project Team Copyright (C)
     *  license http://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh
     */

    namespace app\admin\controller\v2;
    use app\common\controller\AdminController;

    class Setting extends AdminController {

        const GROUP_LIST = [
            '1' => [
                'name' => '基本配置',
                'config' => []
            ],
            '2' => [
                'name' => '商城配置',
                'config' => []
            ],
            '3' => [
                'name' => '上传配置',
                'config' => []
            ],
        ];

        public function initialize() {
            parent::initialize(); // TODO: Change the autogenerated stub
        }

        public function index(){
            if($this->request->isPost()){
                $configs = $this->request->post('config');
                foreach ($configs as $k => $v) {
                    db('system')->where("id = {$k}")->update(['content' => $v]);
                }
                clear_cache();
                insert_admin_log('更新基本设置');
                return $this->returnJson([],'配置成功',1);
            }
            $list = db('system')->order('sort')->select();
            $group_list = self::GROUP_LIST;
            foreach ($list as $key => $item){
                array_push($group_list["{$item['channel']}"]['config'],$item);
            }
            return $this->fetch('index',['list'=>$group_list]);
        }
    }